### ISSUE TITLE
Non existant containers ommited

### ISSUE THREAD

**Issue by dimtion** [timdaman/check_docker#18]
Hi, 

It seems that if I watch multiple containers, and if one of them doesn't exist, no alert is raised. I'm not sure if this is wanted, but it is a strange behaviour anyway.

I assume the problem is in the function `get_containers(names)` when doing the regex matching an exception could be thrown when `re.match("^{}$".format(matcher), found)` is False.

Thanks for the plugin !

**Comment by timdaman** [comment]
I see the issue you are talking about. If you want to ensure a container is in a running state and someone goes ahead and deletes it the check will simply ignore the missing container rather than go critical.  I created a modified version of the check that adds a --present switch to enforce all 'names' must find a match. Can you tell me what you think before I merge it.
https://raw.githubusercontent.com/timdaman/check_docker/enforce_present/check_docker

**Comment by dimtion** [comment]
Thanks for the fast follow up!

The plugin works well, and as intended with the `--present` flag.

Thanks again!

**Comment by timdaman** [comment]
I just pushed version 1.0.4 to PyPi which adds the --present flag. Thank you for the suggestion.
