### ISSUE TITLE
Check_swarm Error

### ISSUE THREAD

**Issue by mrmcox** [timdaman/check_docker#24]
Hi, 

When running the check_swarm command I am getting the following, what am I missing? Thanks!
`./check_swarm --secure-connection localhost:2377 --service capture`

`UNKNOWN: Exception raised during check: URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)'),)
`

**Comment by timdaman** [comment]
Hi, I cannot recreate you environment so some of this is a guess. 

From the message it seems clear that check_swarm was able to speak with your docker daemon, otherwise it would have giving a connection error. The message seems to point to the fact the TLS certificate presented by the remote docker daemon is not trusted. Unless you went through special effort to obtain a certificate it is likely 'self signed'. 

You likely need to do one of the following to resolve this.

- Install the self signed certificate in your systems root store.
- Obtain a 'real certificate' (likely purchased) and install in the docker daemon.
- Use the docker socket file since I see you are connecting on localhost (note: you cannot purchase certificates for localhost).
- Turn on a unencrypted listener in docker daemon and switch to using a unsecured connection, `--connection`

Googling for topics on 'self-signed certificates' and 'how SSL certificates work' may help you understand the issue this message is about.

**Comment by timdaman** [comment]
I am going to close this issue. If you still think there are issues with the check_swarm script feel free to reopen with more details.

**Comment by mrmcox** [comment]
I suspect the issue is with our setup, I am still investigating.

**Comment by fear** [comment]
i have the same issue. a ignore SSL_VERIVICATION would be greate. is this possible to implement?
