### ISSUE TITLE
Docker unrechable return UNKNOWN

### ISSUE THREAD

**Issue by sourceindex** [timdaman/check_docker#8]
Hi @timdaman,

the default behavior of the check when docker is unrechable is at that stage UNKNOWN. 

`
/usr/local/bin/check_docker/check_docker.py --connection /run/docker.sock --health
UNKNOWN: Cannot access docker socket file. User ID=0, socket file=/run/docker.sock
`

According to the numerous backend changes in dockers updates and the criticality of that component, wouldn't it be a good idea to change it it to default CRITICAL? 

Or was there a different decision behind it?

Thanks and greetings,
Sebastian

**Comment by timdaman** [comment]
There is some guidance here but it is somewhat unclear and contradictory.
https://nagios-plugins.org/doc/guidelines.html#AEN78

My reasoning is the following

OK, Warning, Critical say something about the thing you intend to monitor; your service, container, etc.
'Unknown' is in an indicator about other things getting in the way of the check; a bug in the monitor itself, it's configuration, the network, etc. 

Since this failure is with the system or plugin configuration, not the container(s) being monitored, I chose to return unknown.

It is a bit of a judgement call but both do create notifications.
